# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s = "Hi there Sam!"
spil=s.split(' ')
print(spil)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
planet = "Earth"
diameter = 12742
result = "The diameter of {planet} is {diameter} kilometers.".format(planet = "Earth",diameter = 12742)
print(result)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
dic=d['k1'][3]
dicti=dic['tricky'][3]
result=dicti['target'][3]
print(result)

hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
import numpy as np
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
import numpy as np
arr=np.ones(10)*5
print(arr)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
import numpy as np
arr=np.arange(20,36,2)
print(arr)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result=np.concatenate((a,b),axis=0)
print(result)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd

In [14]:
import pandas as pd
data={'name' :['Suba','Nalina','Purnaa'],
      'marks' : [95,97,95]}
df=pd.DataFrame(data)
print(df)

     name  marks
0    Suba     95
1  Nalina     97
2  Purnaa     95


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
import pandas as pd
for i in range(1,32):
    result= "{date} {mnth} {year}".format(date = i, mnth="Jan" ,year="2023")
    data={result}
    df=pd.DataFrame(data)
    print(df)
for i in range(1,11):
    res= "{date} {mnth} {year}".format(date = i, mnth="feb" ,year="2023")
    data={res}
    df=pd.DataFrame(data)
    print(df)

            0
0  1 Jan 2023
            0
0  2 Jan 2023
            0
0  3 Jan 2023
            0
0  4 Jan 2023
            0
0  5 Jan 2023
            0
0  6 Jan 2023
            0
0  7 Jan 2023
            0
0  8 Jan 2023
            0
0  9 Jan 2023
             0
0  10 Jan 2023
             0
0  11 Jan 2023
             0
0  12 Jan 2023
             0
0  13 Jan 2023
             0
0  14 Jan 2023
             0
0  15 Jan 2023
             0
0  16 Jan 2023
             0
0  17 Jan 2023
             0
0  18 Jan 2023
             0
0  19 Jan 2023
             0
0  20 Jan 2023
             0
0  21 Jan 2023
             0
0  22 Jan 2023
             0
0  23 Jan 2023
             0
0  24 Jan 2023
             0
0  25 Jan 2023
             0
0  26 Jan 2023
             0
0  27 Jan 2023
             0
0  28 Jan 2023
             0
0  29 Jan 2023
             0
0  30 Jan 2023
             0
0  31 Jan 2023
            0
0  1 feb 2023
            0
0  2 feb 2023
            0
0  3 feb 2023
    

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
